server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nursery_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
